services:
  frontend:
    container_name: frontend
    build: 
      context: .
      dockerfile: ./frontend/docker/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    restart: always
    tty: true


  notebook:
    container_name: notebook
    build:
      context: .
      dockerfile: ./notebook/docker/Dockerfile
    ports: 
      - 8888:8888
    volumes: 
      - ./:/app
    restart: always
    tty: true

  pipeline:
    container_name: pipeline
    build:
      context: .
      dockerfile: ./pipeline/docker/Dockerfile
    ports:
      - 8082:8082

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/docker/Dockerfile
    ports: 
      - 81:80
    volumes: 
      - ./:/app
    restart: always
    tty: true

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/docker/Dockerfile
    ports: 
      - 5001:5000
    volumes: 
      - ./:/app
    restart: always
    tty: true

  postgres:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGPASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - ./db/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 82:80
    environment:
      PGADMIN_DEFAULT_EMAIL: yoichiojima@gmail.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    volumes:
      - ./db/pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres:
  pgadmin: