services:
  react:
    container_name: apex-charts
    build: 
      context: .
      dockerfile: ./docker/react/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/app
    restart: always
    tty: true

  fastapi:
    container_name: apex-api
    build: 
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend/:/app
    restart: always
    tty: true