services:
  pipeline:
    container_name: pipeline
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes: 
      - ./:/app
    ports:
      - "8082:8082"
    restart: always
    tty: true